#https://github.com/vagnercardosoweb/docker-php8
version: "3.7"

services:
  php-fpm:
    container_name: servidor_php
    build: ./docker/php
    restart: unless-stopped 
    networks:
      - symfony-network       
    depends_on:
      - mariadb
    volumes:
      - ./app:/var/www/html

  caddy:
    container_name: servidor_web
    image: caddy:2.7.4-alpine
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8484:443"
    networks:
      - symfony-network
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./app:/var/www/html
      - ./docker/logs/caddy/:/var/log/
    depends_on:
      - php-fpm
      - mariadb
  
  mariadb:
    container_name: servidor_mariadb
    image: mariadb
    restart: unless-stopped
    ports:
      - '3306:3306'
    networks:
      - symfony-network
    volumes:
      - './docker/mariadb/mariadb.cnf:/etc/mysql/conf.d/custom.cnf:ro'
      - './docker/mariadb/dbdata:/var/lib/mysql'
    environment:
      MYSQL_DATABASE: gmaoDatabase
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: gmao
      MYSQL_PASSWORD: gmaogmao
  
  phpmyadmin:
    container_name: phpmyadmin    
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mariadb
    ports:
      - "8282:80"
    networks:
      - symfony-network
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=300M
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=root

networks:
  symfony-network:
    driver: bridge
